#!/bin/bash

set -e          # causes the script to exit immediately if any command exits with a non-zero status
set -u          # prevents the script from using unset variables
set -o pipefail # exit status of the entire pipeline is the exit status of the last command that failed

if [[ $# -eq 0 ]]; then
  echo "usage: $0 <username>"
  exit 1
fi

# make sure you have GH_TOKEN in your env

USERNAME=$1

function check_username() {
  r=$(
    curl \
      -skL \
      -o tmp \
      -w "%{http_code}" \
      "https://github.com/signup_check/username?value=$USERNAME"
  )

  if [[ $r -eq 422 ]]; then
    echo "username taken"
    exit 1
  else
    echo "username might be available"
    exit 0
  fi
}

check_username
