#!/bin/bash

set -e          # causes the script to exit immediately if any command exits with a non-zero status
set -u          # prevents the script from using unset variables
set -o pipefail # exit status of the entire pipeline is the exit status of the last command that failed

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <gh_org>"
  exit 1
fi

ORG=$1

response=$(
	curl -I -s -o /dev/null -w "%{http_code}" https://api.github.com/orgs/$ORG \
		-H "authorization: token $GH_TOKEN"
)

if [ "$response" -eq 200 ]; then
	echo "true"
elif [ "$response" -eq 404 ]; then
	echo "false"
else
	echo "An error occurred. HTTP status code: $response"
fi
