#!/bin/bash

set -e          # causes the script to exit immediately if any command exits with a non-zero status
set -u          # prevents the script from using unset variables
set -o pipefail # exit status of the entire pipeline is the exit status of the last command that failed

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <projects_lst_file> <product_id>"
  exit 1
fi

# make sure you have KONDUKTO_HOST and KONDUKTO_TOKEN in env

projects_file=$1
prod_id=$2

curl_out="tmp_$(basename $0)"
res=$(
    curl \
      -w "%{http_code}" \
      -o $curl_out \
      -sk \
      -X PATCH \
      "$KONDUKTO_HOST/api/v2/products/$prod_id" \
      --header "X-Cookie: $KONDUKTO_TOKEN" \
      --header 'Content-Type: application/json' \
      --data-raw "{
      \"projects\": [
    $(awk -F':' '{print "        {\"id\": \"" $1 "\"},"}' "$projects_file" | sed '$ s/,$//')
      ]
    }"
  )
  if [[ $res -eq 200 ]]; then
    echo "$(date):INFO:success - now $(cat $curl_out | jq '.product.name') has $(cat $curl_out | jq '.product.projects_count') projects"
    if [[ -n "${DEBUG:-}" ]]; then
      echo "$(date):DEBUG:$(cat $curl_out)"
    fi
    exit
  else
    echo "error: response code: $res message: $(cat $curl_out | jq '.error')"
    exit "$res"
  fi


