#!/bin/bash

set -e          # causes the script to exit immediately if any command exits with a non-zero status
set -u          # prevents the script from using unset variables
set -o pipefail # exit status of the entire pipeline is the exit status of the last command that failed

if [[ $# -ne 3 ]]; then
  echo "usage: $0 <proj_id> <team_name> <team_id>"
  exit 1
fi

# make sure you have KONDUKTO_HOST and KONDUKTO_TOKEN in env

proj_id=$1
team_name=$2
team_id=$3

curl_out="tmp_$(basename $0)"
res=$(
    curl \
      -w "%{http_code}" \
      -o $curl_out \
      -sk \
      -X PATCH \
      "$KONDUKTO_HOST/api/v2/projects/$proj_id" \
      --header "X-Cookie: $KONDUKTO_TOKEN" \
      --header 'Content-Type: application/json' \
      --data-raw "{
      \"name\": \"\",
      \"team\": {
        \"id\": \"$team_id\",
        \"name\": \"$team_name\"
      }
    }"
  )
  if [[ $res -eq 200 ]]; then
    echo "$(date):INFO:success - now $(cat $curl_out | jq '.project.name') is part of $(cat $curl_out | jq '.project.team.name') team"
    if [[ -n "${DEBUG:-}" ]]; then
      echo "$(date):DEBUG:$(cat $curl_out)"
    fi
    exit
  else
    echo "error: response code: $res message: $(cat $curl_out | jq '.error')"
    exit "$res"
  fi


