#!/bin/bash

set -e          # causes the script to exit immediately if any command exits with a non-zero status
set -u          # prevents the script from using unset variables
set -o pipefail # exit status of the entire pipeline is the exit status of the last command that failed

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <project_name>"
  exit 1
fi

project_name=$1
OUT=sbom_scans.json
if [[ -f $OUT ]]; then rm $OUT; fi
curl_out="tmp_$(basename $0)"

pid=$(kdt-get-project-id "$project_name")
if [[ -z $pid ]]; then
  echo "error: project $project_name not found"
  exit 1
fi

get_sboms() {
  local start=0
  local total=0
  local count=-1

  while [[ $count -lt $total ]]; do
    res=$(
      curl \
       -w "%{http_code}" \
       -o "$curl_out" \
       -sk \
        "$KONDUKTO_HOST/api/v2/projects/$pid/sbom/scans?start=$start" \
        --header "X-Cookie: $KONDUKTO_TOKEN"
    )
    if [[ $res -eq 200 ]]; then
      total=$(
        cat $curl_out | jq '.total'
      )

      cat $curl_out | jq -r '.scans[] | .' >> "$OUT"
      count=$(
        cat $OUT | jq -r '.id' | wc -l | tr -d ' '
      )
      start=$count
      echo "$count $total" >&2
    else
      echo "error: response code: $res message: $(cat curl_out | jq '.error')"
      exit 1
    fi
  done
}

get_sboms
