#!/bin/bash

ORG="$1"
TOKEN="$GH_TOKEN"
SLEEP=3 # seconds
PAGE=1
PER_PAGE=100
SCOPE_FILE=repos_in_scope.lst

# Base GitHub API URL
BASE_URL="https://api.github.com"

get_latest_release() {
  url=$1
  local response=$(
    curl -sk -o tmp_repo -w "%{http_code}" $url -H "authorization: token $TOKEN"
  )

  if [ "$response" -eq 200 ]; then
    latest_release=$(cat tmp_repo | jq '.[] | .tag_name' | sed 's/"//g')
    echo "$repo:$latest_release"
  else
    echo "$(date): an error occured. github response code $response"
  fi
}

retries=1
# Loop through all pages
while true; do
  # Make API request for the current page
  response=$(curl -sk -o tmp -w "%{http_code}" -H "authorization: token $TOKEN" "$BASE_URL/orgs/$ORG/repos?per_page=$PER_PAGE&page=$PAGE")
  [[ "$response" -ne 200 ]] && [[ retries -le 3 ]] && sleep $SLEEP && retries=$((retries + 1)) &&
    echo "$(date): github response code $response, retrying ..." && continue
  retries=1

  # Check if the response contains any repositories
  if [[ $(cat tmp | jq '. | length') -eq 0 ]]; then
    echo "ERROR"
    break
  fi

  cat tmp | jq -r '.[] | .releases_url' | while read url; do
    repo=$(echo $url | cut -d '/' -f 6)
    url="$(echo $url | sed 's/{.*//')?per_page=1"

    if [[ -f $SCOPE_FILE ]]; then
      while IFS= read -r regex; do
        if [[ "$repo" =~ $regex ]]; then
          sleep 1
          get_latest_release $url
          break
        fi
      done <$SCOPE_FILE
    else
      get_latest_release $url
    fi
  done

  # Check for the 'Link' header to see if there are more pages
  LINK_HEADER=$(curl -Isk -H "Authorization: token $TOKEN" "$BASE_URL/orgs/$ORG/repos?per_page=$PER_PAGE&page=$PAGE" | grep -i '^Link:')

  # If there is no 'Link' header or it does not contain 'rel="next"', we've reached the last page
  if [[ ! "$LINK_HEADER" =~ 'rel="next"' ]]; then
    break
  fi

  # Move to the next page
  PAGE=$((PAGE + 1))
done
